version: '3.8'
services:
  client-backend:
    image: ago
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:p6spy:mysql://service-db/ago

  service-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: Musavencosi1996

    ports:
      - "3307:3306"
    restart: unless-stopped