spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/ago
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: Musavencosi1996
  jpa:
    hibernate:
      ddl-auto: validate

application:
  scheduled-task: # периодические задания
    retry: # повторная отправка заявок на обработку
      schedule: '0/30 * * * * *' # расписание в формате Spring Cron


